OOP school library: set up associations
udeaghad/school-library pull request #3
Opened 2022-08-31 19:29 UTC by udeaghad

In this pull request, I have

- Created a class Classroom with the required variables
- Created the has-many/belongs-to relationship between Classroom and Student
- Created a class Book with the required variables
- Created a class Rental with the required variables
- Created the many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental

Kindly review and approve.

2022-08-31 21:25 UTC, BenMukebo requested changes
### Hi @udeaghad,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- Descriptive README file.  ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 21:25 UTC, BenMukebo commented on book.rb
> +  attr_reader :rental
- [ ]  Kindly make sure the Getters and Setters for @rentals are present

```ruby
  attr_accessor :title, :author, :rentals
```

2022-08-31 21:25 UTC, BenMukebo commented on book.rb
> +  end
- [OPTIONAL] You need to create the `many-to-many` (also `has-many-through`) relationship between `Person` and `Book` using the intermediate class `Rental`.  Great job creating a method for adding rentals but it should look like this: 

```ruby
  def add_rental(person, date)
    # *the book itself should be sent as a parameter to create the new rental achieving the 'has-many' association. 
    Rental.new(date, self, person)
  end
```

Here is a [link](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) to the example in a previous lesson:

2022-08-31 21:25 UTC, BenMukebo commented on rental.rb
> +
- [ ] Kindly make sure the Getters and Setters for @book and @person instance variables be present 👇🏻 


```ruby
     attr_accessor :date, :book, :person
```

2022-08-31 21:25 UTC, BenMukebo commented on person.rb
> +  end
- [ ] Great job creating a method for adding rentals but it should look like this:

```ruby
 def add_rental(book, date)
    # *The person itself should be sent as a parameter to create the new rental achieving the 'has-many' association
    Rental.new(date, book, self)
  end
```

2022-09-01 10:50 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @udeaghad 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great job on implementing the changes by the previous reviewer ✅
- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅
- No Linter errors ✅


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-01 10:50 UTC, Bondok6 commented on rental.rb
> +  attr_accessor :date, book, :person
- [OPTIONAL] I think there is a typo here, It should be `:book` with simi-colon instead of `book` 👌

2022-09-01 11:33 UTC, merged